### ISSUE TITLE
AttributeError: module 'model.agcn3' has no attribute 'Model2'

### ISSUE THREAD

**Issue by dongle329** [xiaoiker/GCN-NAS#6]
when i run
python main.py --config ./config/nturgbd-cross-view/train_joint.yaml
have this problem 
AttributeError: module 'model.agcn3' has no attribute 'Model2'
but
python main.py --config ./config/nturgbd-cross-setup/train_joint.yaml
python main.py --config ./config/nturgbd-kinetics-skeleton/train_joint.yaml
can run
What kind of mistake is that

**Comment by xiaoiker** [comment]
Hey,

Thanks very much for reporting this issue. This is because you should customize the configure files (all the .yaml files here) depend on your own settings. We are sorry for keeping some debugging settings there. 

For your case, you can simply change the line 27 of ./config/nturgbd-cross-view/train_joint.yaml to model: model.agcn3.Model

Hope this helps.
